// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nk-I7GpxU-RlbGNrqhb1m2txTi8Lf48',
    appId: '1:730643591781:web:5969c3f704264a8a5b4c8c',
    messagingSenderId: '730643591781',
    projectId: 'senior-design-362600',
    authDomain: 'senior-design-362600.firebaseapp.com',
    storageBucket: 'senior-design-362600.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZbJ0NAVmiWe64KaU1NsnjoheXaAbNGvw',
    appId: '1:730643591781:android:89f06387678b351c5b4c8c',
    messagingSenderId: '730643591781',
    projectId: 'senior-design-362600',
    storageBucket: 'senior-design-362600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1bOHjH4BR6TW7W2NJNXk8PoC412haYk',
    appId: '1:730643591781:ios:e126fcde0aaf9dcd5b4c8c',
    messagingSenderId: '730643591781',
    projectId: 'senior-design-362600',
    storageBucket: 'senior-design-362600.appspot.com',
    iosClientId: '730643591781-21snhbtppet011otss3hf0dhch76rhih.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMapsFirestore',
  );
}
